import Head from 'next/head';
import { gsap } from 'gsap/dist/gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';

import GlobalLayout from '@/components/layout/GlobalLayout';
import S01 from './main/S01';
import S02 from './main/S02';
import S03 from './main/S03';
import S04 from './main/S04';
import S05 from './main/S05';

const Page = () => {
  gsap.registerPlugin(ScrollTrigger);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <S01 />
        <S02 />
        <S03 />
        <S04 />
        <S05 />
      </div>
    </div>
  );
};

Page.getLayout = (page) => <GlobalLayout>{page}</GlobalLayout>;

export default Page;
